from __future__ import annotations

import pandas as pd
import torch

from torch_spa.core import solar_position


def test_one() -> None:
    # -- arguments -- #
    lats = 40
    lons = -105
    datetimes = ["2010-06-21 00:06:00", "2010-06-21 00:12:00"]

    data = solar_position(datetimes, lats, lons).squeeze()

    torch.testing.assert_close(
        data.azimuth,
        torch.tensor([280.3651, 281.2308]).double(),
        atol=1e-2,
        rtol=1e-2,
        check_dtype=False,
    )

    torch.testing.assert_close(
        data.elevation,
        torch.tensor([25.16378, 24.03705]).double(),
        atol=1e-2,
        rtol=1e-2,
        check_dtype=False,
    )


def test_noaa_comparison() -> None:
    # -- arguments -- #
    # type: ignore
    test_file = "assets/NOAA_Solar_Calculations_day.csv"
    # the csv test file was generated by the NOAA Solar Calculator
    # using the following parameters:
    lats = 40
    lons = -105
    df = pd.read_csv(test_file, index_col=0)

    test_azimuth = torch.from_numpy(df["Solar Azimuth Angle (deg cw from N)"].to_numpy())
    test_elev = torch.from_numpy(df["Solar Elevation Angle (deg)"].to_numpy())
    datetimes = pd.to_datetime(df["Date"] + " " + df["Time (past local midnight)"])

    data = solar_position(datetimes, lats, lons)

    AZ = data.azimuth.squeeze()
    EL = data.elevation.squeeze()

    # azimuth
    torch.testing.assert_close(AZ, test_azimuth, atol=0.1, rtol=1e-2, check_dtype=False)

    # elevation
    torch.testing.assert_close(EL, test_elev, atol=0.75, rtol=1e-2, check_dtype=False)
